webtalk_init -webtalk_dir F:/A_viraj drive/AMtech/HDL/Practical/Practical 8/U_D_bh_8b/U_D_bh_8b.sim/sim_1/behav/xsim/xsim.dir/Tb_U_D_bh_8b_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Sep 16 01:06:46 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "edf3e42f-7921-4443-a03a-58df7b6f0cc8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f8ba508f7f97484ebddf9ef497f2cea4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5376_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2868346362 -regid "" -xml F:/A_viraj drive/AMtech/HDL/Practical/Practical 8/U_D_bh_8b/U_D_bh_8b.sim/sim_1/behav/xsim/xsim.dir/Tb_U_D_bh_8b_behav/webtalk/usage_statistics_ext_xsim.xml -html F:/A_viraj drive/AMtech/HDL/Practical/Practical 8/U_D_bh_8b/U_D_bh_8b.sim/sim_1/behav/xsim/xsim.dir/Tb_U_D_bh_8b_behav/webtalk/usage_statistics_ext_xsim.html -wdm F:/A_viraj drive/AMtech/HDL/Practical/Practical 8/U_D_bh_8b/U_D_bh_8b.sim/sim_1/behav/xsim/xsim.dir/Tb_U_D_bh_8b_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
